import img1 from '../image/1.jpg'
import img2 from '../image/2.jpg'
import img3 from '../image/3.jpg'
import img4 from '../image/4.jpg'
import img5 from '../image/5.jpg'
import img6 from '../image/6.jpg'
import img7 from '../image/7.jpg'
import img8 from '../image/8.jpg'
import img9 from '../image/9.jpg'
import img10 from '../image/10.jpg'
import img11 from '../image/11.jpg'
import img12 from '../image/12.jpg'
import img13 from '../image/13.jpg'
import img14 from '../image/14.jpg'
import img15 from '../image/15.jpg'
import img16 from '../image/16.jpg'
import img17 from '../image/17.jpg'
import img18 from '../image/18.jpg'
import img19 from '../image/19.jpg'
import img20 from '../image/1.jpg'
import img21 from '../image/20.jpg'
import img22 from '../image/21.jpg'
import img23 from '../image/22.jpg'
import img24 from '../image/23.jpg'
import img25 from '../image/24.jpg'
import img26 from '../image/25.jpg'
import img27 from '../image/26.jpg'
import img28 from '../image/27.jpg'
import img29 from '../image/28.jpg'
import img30 from '../image/29.jpg'
import img31 from '../image/30.jpg'
import img32 from '../image/31.jpg'
import img33 from '../image/32.jpg'
import img34 from '../image/33.jpg'
import img35 from '../image/34.jpg'
import img36 from '../image/35.jpg'
import img37 from '../image/36.jpg'
import img38 from '../image/37.jpg'
import img39 from '../image/38.jpg'
const MovieData = [
    {id: 1, title: 'Baahubali 2', director: 'S. S. Rajamouli', cast: 'Prabhas, Rana Daggubati, Anushka Shetty, Sathyaraj, Ramya Krishnan, Tamannaah Bhatia',release: '28 April 2017 ',description: 'Even though it’s not a Bollywood film, it did wonders to the Indian box-office. Directed by S. S. Rajamouli, Baahubali 2: The Conclusion went on to become the highest grossing film of the decade with an earning of about Rs. 510.99 crores at the Indian box-office. The magnum-opus mythological drama made on a budget of Rs 250 crores, broke all box-office records becoming the highest-grossing Hindi film of all time.', img: img1, time: '3pm to 6pm', count: 1},
    {id: 2, title: 'Dangal', director: 'Nitesh Tiwari', cast: 'Aamir Khan, Fatima Sana Shaikh, Sanya Malhotra, Zaira Wasim',release: '23 December 2016',description: 'Based on the life of two Commonwealth gold-medalist sisters, Geeta Phogat and Babita Kumari from Haryana, Aamir Khan starrer Dangal is the second highest grossing film of the decade. The film released in 2016 and went onto win several awards at the 62nd Filmfare Awards. Aamir Khan in the role of an uplifting and hardworking father and Fatima Sana Shaikh and Sanya Malhotra as the Phogat sisters won over the audiences with their stellar performances.', img: img2, time: '6pm to 9pm', count: 1},
    {id: 3, title: 'Sanju', director: 'Rajkumar Hirani', cast: 'Ranbir Kapoor, Anushka Sharman, Sonam Kapoor, Vicky Kaushal, Dia Mirza',release: '29 June 2018',description: 'Another Rajkumar Hirani directorial that became a blockbuster was the Sanjay Dutt biopic, Sanju. Ranbir Kapoor starrer narrates the real life controversial story of the mega star Sanjay Dutt showing his highest highs and lowest lows. Hirani’s brilliant story-telling and Ranbir’s mind blowing performance made Sanju one of the most loved films of the year.', img: img3, time: '2pm to 6pm', count: 1},
    {id: 4, title: 'PK', director: ' Rajkumar Hirani', cast: 'Aamir Khan, Anushka Sharma, Sushant Singh Rajput, Boman Irani, Sanjay Dutt',release: '19 December 2014 ',description: 'This period drama featured Deepika Padukone as Rani Padmavati, alongside Shahid Kapoor as Maharawal Ratan Singh and Ranveer Singh as Alauddin Khilji. Bhansali period drama was made on extravagant film sets and costumes and the finest actors. The film had to deal with a lot of controversies and life-threatening protests due to its plot but it still made it to the list of highest grossing films between 2010-2019 at the eighth position', img: img4},
    {id: 5, title: 'Tiger Zinda Hai', director: 'Ali Abbas Zafar', cast: 'Salman Khan, Katrina Kaif',release: '28 April 2017 ',description: 'A sequel to the blockbuster Ek Tha Tiger, Tiger Zinda Hai was a story of two super spies Tiger, Salman Khan and Zoya, Katrina Kaif.  Ali Abbas Zafar directorial was an action-packed entertainer with Salman Khan written all over it. Earning Rs. 339 crore at the Indian box-office, Tiger Zinda Hai is the fifth highest grossing film of the decade.', img: img5, time: '3pm to 6pm'},
    {id: 6, title: 'Bajrangi Bhaijaan', director: ' Kabir Khan', cast: ' Salman Khan, Harshaali Malhotra, Nawazuddin Siddiqui',release: '28 April 2017 ',description: 'Second Salman Khan starrer to enter the list is the 2015 release, Bajrangi Bhaijaan. This Kabir Khan directorial potrayed Salman in a different light from his usual roles. Essaying the role of a simple Indian man, Pawan Kumar Chaturvedi, an ardent follower of God Bajrangbali this became one of Salman’s most memorable roles.', img: img6, time: '3:30pm to 6:30pm'},
    {id: 7, title: 'War', director: 'Sanjay Leela Bhansali', cast: ' Hrithik Roshan, Tiger Shroff, Vaani Kapoor',release: '28 April 2017 ',description: 'Hrithik Roshan and Tiger Shroff starrer War was a hardcore action film. With two handsome hunks flaunting their chiselled bodies in high-octane action sequences, the film served to be a delight for Tiger and Hrithik’s fans. From action, drama, romance to music, War had the right amount of everything hence making it a huge box-office success in 2019.', img: img7, time: '3pm to 6pm'},
    {id: 8, title: 'Padmaavat', director: 'Sanjay Leela Bhansali', cast: 'Deepika Padukone, Ranveer Singh, Shahid Kapoor',release: '28 April 2017 ',description: 'This period drama featured Deepika Padukone as Rani Padmavati, alongside Shahid Kapoor as Maharawal Ratan Singh and Ranveer Singh as Alauddin Khilji. Bhansali period drama was made on extravagant film sets and costumes and the finest actors. The film had to deal with a lot of controversies and life-threatening protests due to its plot but it still made it to the list of highest grossing films between 2010-2019 at the eighth position', img: img8, time: '5pm to 7pm'},
    {id: 9, title: 'Sultan ', director: 'Ali Abbas Zafar', cast: 'Salman Khan, Anushka Sharma',release: '28 April 2017 ',description: "Yet another Ali Abbas Zafar – Salman collaboration that made to the list is Sultan. The film was a classic underdog tale about a wrestler's journey named Sultan Ali Khan. The film also starred Anushka Sharma as Salman’s love interest Aarfa. With power packed performances from both Salman and Anushka, this emotional drama striked the right chords with the audiences and made a mark at the box-office.", img: img9, time: '3pm to 6pm'},
    {id: 10, title: 'Dhoom 3', director: 'Vijay Krishna Acharya', cast: 'Aamir Khan, Katrina Kaif, Abhishek Bachchan, Uday Chopra',release: '28 April 2017 ',description: "Dhoom 3 marked the third installment of the hit Dhoom franchise. The action packed thriller Aamir plays Sahir, a circus entertainer who attempts for a bank robbery in Chicago in order to take revenge of his father's death. Inspector Jai and Ali played by Abhishek and Uday play the cops on duty as they investigate the case. This marks the third Aamir starrer to the list of the highest grosses in the last decade.", img: img10, time: '10am to 1pm'},
    

    {id: 11, title: 'Dhoom 3', director: 'Vijay Krishna Acharya', cast: 'Aamir Khan, Katrina Kaif, Abhishek Bachchan, Uday Chopra',release: '28 April 2017 ',description: "Dhoom 3 marked the third installment of the hit Dhoom franchise. The action packed thriller Aamir plays Sahir, a circus entertainer who attempts for a bank robbery in Chicago in order to take revenge of his father's death. Inspector Jai and Ali played by Abhishek and Uday play the cops on duty as they investigate the case. This marks the third Aamir starrer to the list of the highest grosses in the last decade.", img: img39, time: '10am to 1pm'},
    {id: 12, title: 'Dhoom 3', director: 'Vijay Krishna Acharya', cast: 'Aamir Khan, Katrina Kaif, Abhishek Bachchan, Uday Chopra',release: '28 April 2017 ',description: "Dhoom 3 marked the third installment of the hit Dhoom franchise. The action packed thriller Aamir plays Sahir, a circus entertainer who attempts for a bank robbery in Chicago in order to take revenge of his father's death. Inspector Jai and Ali played by Abhishek and Uday play the cops on duty as they investigate the case. This marks the third Aamir starrer to the list of the highest grosses in the last decade.", img: img11, time: '10am to 1pm'},
    {id: 13, title: 'Dhoom 3', director: 'Vijay Krishna Acharya', cast: 'Aamir Khan, Katrina Kaif, Abhishek Bachchan, Uday Chopra',release: '28 April 2017 ',description: "Dhoom 3 marked the third installment of the hit Dhoom franchise. The action packed thriller Aamir plays Sahir, a circus entertainer who attempts for a bank robbery in Chicago in order to take revenge of his father's death. Inspector Jai and Ali played by Abhishek and Uday play the cops on duty as they investigate the case. This marks the third Aamir starrer to the list of the highest grosses in the last decade.", img: img12, time: '10am to 1pm'},
    {id: 14, title: 'Dhoom 3', director: 'Vijay Krishna Acharya', cast: 'Aamir Khan, Katrina Kaif, Abhishek Bachchan, Uday Chopra',release: '28 April 2017 ',description: "Dhoom 3 marked the third installment of the hit Dhoom franchise. The action packed thriller Aamir plays Sahir, a circus entertainer who attempts for a bank robbery in Chicago in order to take revenge of his father's death. Inspector Jai and Ali played by Abhishek and Uday play the cops on duty as they investigate the case. This marks the third Aamir starrer to the list of the highest grosses in the last decade.", img: img13, time: '10am to 1pm'},
    {id: 15, title: 'Dhoom 3', director: 'Vijay Krishna Acharya', cast: 'Aamir Khan, Katrina Kaif, Abhishek Bachchan, Uday Chopra',release: '28 April 2017 ',description: "Dhoom 3 marked the third installment of the hit Dhoom franchise. The action packed thriller Aamir plays Sahir, a circus entertainer who attempts for a bank robbery in Chicago in order to take revenge of his father's death. Inspector Jai and Ali played by Abhishek and Uday play the cops on duty as they investigate the case. This marks the third Aamir starrer to the list of the highest grosses in the last decade.", img: img14, time: '10am to 1pm'},
    {id: 16, title: 'Dhoom 3', director: 'Vijay Krishna Acharya', cast: 'Aamir Khan, Katrina Kaif, Abhishek Bachchan, Uday Chopra',release: '28 April 2017 ',description: "Dhoom 3 marked the third installment of the hit Dhoom franchise. The action packed thriller Aamir plays Sahir, a circus entertainer who attempts for a bank robbery in Chicago in order to take revenge of his father's death. Inspector Jai and Ali played by Abhishek and Uday play the cops on duty as they investigate the case. This marks the third Aamir starrer to the list of the highest grosses in the last decade.", img: img15, time: '10am to 1pm'},
    {id: 17, title: 'Dhoom 3', director: 'Vijay Krishna Acharya', cast: 'Aamir Khan, Katrina Kaif, Abhishek Bachchan, Uday Chopra',release: '28 April 2017 ',description: "Dhoom 3 marked the third installment of the hit Dhoom franchise. The action packed thriller Aamir plays Sahir, a circus entertainer who attempts for a bank robbery in Chicago in order to take revenge of his father's death. Inspector Jai and Ali played by Abhishek and Uday play the cops on duty as they investigate the case. This marks the third Aamir starrer to the list of the highest grosses in the last decade.", img: img16, time: '10am to 1pm'},
    {id: 18, title: 'Dhoom 3', director: 'Vijay Krishna Acharya', cast: 'Aamir Khan, Katrina Kaif, Abhishek Bachchan, Uday Chopra',release: '28 April 2017 ',description: "Dhoom 3 marked the third installment of the hit Dhoom franchise. The action packed thriller Aamir plays Sahir, a circus entertainer who attempts for a bank robbery in Chicago in order to take revenge of his father's death. Inspector Jai and Ali played by Abhishek and Uday play the cops on duty as they investigate the case. This marks the third Aamir starrer to the list of the highest grosses in the last decade.", img: img17, time: '10am to 1pm'},
    {id: 19, title: 'Dhoom 3', director: 'Vijay Krishna Acharya', cast: 'Aamir Khan, Katrina Kaif, Abhishek Bachchan, Uday Chopra',release: '28 April 2017 ',description: "Dhoom 3 marked the third installment of the hit Dhoom franchise. The action packed thriller Aamir plays Sahir, a circus entertainer who attempts for a bank robbery in Chicago in order to take revenge of his father's death. Inspector Jai and Ali played by Abhishek and Uday play the cops on duty as they investigate the case. This marks the third Aamir starrer to the list of the highest grosses in the last decade.", img: img18, time: '10am to 1pm'},
    {id: 20, title: 'Dhoom 3', director: 'Vijay Krishna Acharya', cast: 'Aamir Khan, Katrina Kaif, Abhishek Bachchan, Uday Chopra',release: '28 April 2017 ',description: "Dhoom 3 marked the third installment of the hit Dhoom franchise. The action packed thriller Aamir plays Sahir, a circus entertainer who attempts for a bank robbery in Chicago in order to take revenge of his father's death. Inspector Jai and Ali played by Abhishek and Uday play the cops on duty as they investigate the case. This marks the third Aamir starrer to the list of the highest grosses in the last decade.", img: img19, time: '10am to 1pm'},
    {id: 21, title: 'Dhoom 3', director: 'Vijay Krishna Acharya', cast: 'Aamir Khan, Katrina Kaif, Abhishek Bachchan, Uday Chopra',release: '28 April 2017 ',description: "Dhoom 3 marked the third installment of the hit Dhoom franchise. The action packed thriller Aamir plays Sahir, a circus entertainer who attempts for a bank robbery in Chicago in order to take revenge of his father's death. Inspector Jai and Ali played by Abhishek and Uday play the cops on duty as they investigate the case. This marks the third Aamir starrer to the list of the highest grosses in the last decade.", img: img20, time: '10am to 1pm'},
    {id: 22, title: 'Dhoom 3', director: 'Vijay Krishna Acharya', cast: 'Aamir Khan, Katrina Kaif, Abhishek Bachchan, Uday Chopra',release: '28 April 2017 ',description: "Dhoom 3 marked the third installment of the hit Dhoom franchise. The action packed thriller Aamir plays Sahir, a circus entertainer who attempts for a bank robbery in Chicago in order to take revenge of his father's death. Inspector Jai and Ali played by Abhishek and Uday play the cops on duty as they investigate the case. This marks the third Aamir starrer to the list of the highest grosses in the last decade.", img: img21, time: '10am to 1pm'},

    {id: 23, title: 'Dhoom 3', director: 'Vijay Krishna Acharya', cast: 'Aamir Khan, Katrina Kaif, Abhishek Bachchan, Uday Chopra',release: '28 April 2017 ',description: "Dhoom 3 marked the third installment of the hit Dhoom franchise. The action packed thriller Aamir plays Sahir, a circus entertainer who attempts for a bank robbery in Chicago in order to take revenge of his father's death. Inspector Jai and Ali played by Abhishek and Uday play the cops on duty as they investigate the case. This marks the third Aamir starrer to the list of the highest grosses in the last decade.", img: img22, time: '10am to 1pm'},
    {id: 24, title: 'Dhoom 3', director: 'Vijay Krishna Acharya', cast: 'Aamir Khan, Katrina Kaif, Abhishek Bachchan, Uday Chopra',release: '28 April 2017 ',description: "Dhoom 3 marked the third installment of the hit Dhoom franchise. The action packed thriller Aamir plays Sahir, a circus entertainer who attempts for a bank robbery in Chicago in order to take revenge of his father's death. Inspector Jai and Ali played by Abhishek and Uday play the cops on duty as they investigate the case. This marks the third Aamir starrer to the list of the highest grosses in the last decade.", img: img23, time: '10am to 1pm'},
    {id: 25, title: 'Dhoom 3', director: 'Vijay Krishna Acharya', cast: 'Aamir Khan, Katrina Kaif, Abhishek Bachchan, Uday Chopra',release: '28 April 2017 ',description: "Dhoom 3 marked the third installment of the hit Dhoom franchise. The action packed thriller Aamir plays Sahir, a circus entertainer who attempts for a bank robbery in Chicago in order to take revenge of his father's death. Inspector Jai and Ali played by Abhishek and Uday play the cops on duty as they investigate the case. This marks the third Aamir starrer to the list of the highest grosses in the last decade.", img: img24, time: '10am to 1pm'},
    {id: 26, title: 'Dhoom 3', director: 'Vijay Krishna Acharya', cast: 'Aamir Khan, Katrina Kaif, Abhishek Bachchan, Uday Chopra',release: '28 April 2017 ',description: "Dhoom 3 marked the third installment of the hit Dhoom franchise. The action packed thriller Aamir plays Sahir, a circus entertainer who attempts for a bank robbery in Chicago in order to take revenge of his father's death. Inspector Jai and Ali played by Abhishek and Uday play the cops on duty as they investigate the case. This marks the third Aamir starrer to the list of the highest grosses in the last decade.", img: img25, time: '10am to 1pm'},
    {id: 27, title: 'Dhoom 3', director: 'Vijay Krishna Acharya', cast: 'Aamir Khan, Katrina Kaif, Abhishek Bachchan, Uday Chopra',release: '28 April 2017 ',description: "Dhoom 3 marked the third installment of the hit Dhoom franchise. The action packed thriller Aamir plays Sahir, a circus entertainer who attempts for a bank robbery in Chicago in order to take revenge of his father's death. Inspector Jai and Ali played by Abhishek and Uday play the cops on duty as they investigate the case. This marks the third Aamir starrer to the list of the highest grosses in the last decade.", img: img26, time: '10am to 1pm'},
    {id: 28, title: 'Dhoom 3', director: 'Vijay Krishna Acharya', cast: 'Aamir Khan, Katrina Kaif, Abhishek Bachchan, Uday Chopra',release: '28 April 2017 ',description: "Dhoom 3 marked the third installment of the hit Dhoom franchise. The action packed thriller Aamir plays Sahir, a circus entertainer who attempts for a bank robbery in Chicago in order to take revenge of his father's death. Inspector Jai and Ali played by Abhishek and Uday play the cops on duty as they investigate the case. This marks the third Aamir starrer to the list of the highest grosses in the last decade.", img: img27, time: '10am to 1pm'},
    {id: 29, title: 'Dhoom 3', director: 'Vijay Krishna Acharya', cast: 'Aamir Khan, Katrina Kaif, Abhishek Bachchan, Uday Chopra',release: '28 April 2017 ',description: "Dhoom 3 marked the third installment of the hit Dhoom franchise. The action packed thriller Aamir plays Sahir, a circus entertainer who attempts for a bank robbery in Chicago in order to take revenge of his father's death. Inspector Jai and Ali played by Abhishek and Uday play the cops on duty as they investigate the case. This marks the third Aamir starrer to the list of the highest grosses in the last decade.", img: img28, time: '10am to 1pm'},
    {id: 30, title: 'Dhoom 3', director: 'Vijay Krishna Acharya', cast: 'Aamir Khan, Katrina Kaif, Abhishek Bachchan, Uday Chopra',release: '28 April 2017 ',description: "Dhoom 3 marked the third installment of the hit Dhoom franchise. The action packed thriller Aamir plays Sahir, a circus entertainer who attempts for a bank robbery in Chicago in order to take revenge of his father's death. Inspector Jai and Ali played by Abhishek and Uday play the cops on duty as they investigate the case. This marks the third Aamir starrer to the list of the highest grosses in the last decade.", img: img29, time: '10am to 1pm'},
    {id: 31, title: 'Dhoom 3', director: 'Vijay Krishna Acharya', cast: 'Aamir Khan, Katrina Kaif, Abhishek Bachchan, Uday Chopra',release: '28 April 2017 ',description: "Dhoom 3 marked the third installment of the hit Dhoom franchise. The action packed thriller Aamir plays Sahir, a circus entertainer who attempts for a bank robbery in Chicago in order to take revenge of his father's death. Inspector Jai and Ali played by Abhishek and Uday play the cops on duty as they investigate the case. This marks the third Aamir starrer to the list of the highest grosses in the last decade.", img: img30, time: '10am to 1pm'},
    {id: 32, title: 'Dhoom 3', director: 'Vijay Krishna Acharya', cast: 'Aamir Khan, Katrina Kaif, Abhishek Bachchan, Uday Chopra',release: '28 April 2017 ',description: "Dhoom 3 marked the third installment of the hit Dhoom franchise. The action packed thriller Aamir plays Sahir, a circus entertainer who attempts for a bank robbery in Chicago in order to take revenge of his father's death. Inspector Jai and Ali played by Abhishek and Uday play the cops on duty as they investigate the case. This marks the third Aamir starrer to the list of the highest grosses in the last decade.", img: img31, time: '10am to 1pm'},
    {id: 33, title: 'Dhoom 3', director: 'Vijay Krishna Acharya', cast: 'Aamir Khan, Katrina Kaif, Abhishek Bachchan, Uday Chopra',release: '28 April 2017 ',description: "Dhoom 3 marked the third installment of the hit Dhoom franchise. The action packed thriller Aamir plays Sahir, a circus entertainer who attempts for a bank robbery in Chicago in order to take revenge of his father's death. Inspector Jai and Ali played by Abhishek and Uday play the cops on duty as they investigate the case. This marks the third Aamir starrer to the list of the highest grosses in the last decade.", img: img32, time: '10am to 1pm'},
    {id: 34, title: 'Dhoom 3', director: 'Vijay Krishna Acharya', cast: 'Aamir Khan, Katrina Kaif, Abhishek Bachchan, Uday Chopra',release: '28 April 2017 ',description: "Dhoom 3 marked the third installment of the hit Dhoom franchise. The action packed thriller Aamir plays Sahir, a circus entertainer who attempts for a bank robbery in Chicago in order to take revenge of his father's death. Inspector Jai and Ali played by Abhishek and Uday play the cops on duty as they investigate the case. This marks the third Aamir starrer to the list of the highest grosses in the last decade.", img: img33, time: '10am to 1pm'},
    {id: 35, title: 'Dhoom 3', director: 'Vijay Krishna Acharya', cast: 'Aamir Khan, Katrina Kaif, Abhishek Bachchan, Uday Chopra',release: '28 April 2017 ',description: "Dhoom 3 marked the third installment of the hit Dhoom franchise. The action packed thriller Aamir plays Sahir, a circus entertainer who attempts for a bank robbery in Chicago in order to take revenge of his father's death. Inspector Jai and Ali played by Abhishek and Uday play the cops on duty as they investigate the case. This marks the third Aamir starrer to the list of the highest grosses in the last decade.", img: img34, time: '10am to 1pm'},
    {id: 36, title: 'Dhoom 3', director: 'Vijay Krishna Acharya', cast: 'Aamir Khan, Katrina Kaif, Abhishek Bachchan, Uday Chopra',release: '28 April 2017 ',description: "Dhoom 3 marked the third installment of the hit Dhoom franchise. The action packed thriller Aamir plays Sahir, a circus entertainer who attempts for a bank robbery in Chicago in order to take revenge of his father's death. Inspector Jai and Ali played by Abhishek and Uday play the cops on duty as they investigate the case. This marks the third Aamir starrer to the list of the highest grosses in the last decade.", img: img35, time: '10am to 1pm'},
    {id: 37, title: 'Dhoom 3', director: 'Vijay Krishna Acharya', cast: 'Aamir Khan, Katrina Kaif, Abhishek Bachchan, Uday Chopra',release: '28 April 2017 ',description: "Dhoom 3 marked the third installment of the hit Dhoom franchise. The action packed thriller Aamir plays Sahir, a circus entertainer who attempts for a bank robbery in Chicago in order to take revenge of his father's death. Inspector Jai and Ali played by Abhishek and Uday play the cops on duty as they investigate the case. This marks the third Aamir starrer to the list of the highest grosses in the last decade.", img: img36, time: '10am to 1pm'},
    {id: 38, title: 'Dhoom 3', director: 'Vijay Krishna Acharya', cast: 'Aamir Khan, Katrina Kaif, Abhishek Bachchan, Uday Chopra',release: '28 April 2017 ',description: "Dhoom 3 marked the third installment of the hit Dhoom franchise. The action packed thriller Aamir plays Sahir, a circus entertainer who attempts for a bank robbery in Chicago in order to take revenge of his father's death. Inspector Jai and Ali played by Abhishek and Uday play the cops on duty as they investigate the case. This marks the third Aamir starrer to the list of the highest grosses in the last decade.", img: img37, time: '10am to 1pm'},
    {id: 39, title: 'Dhoom 3', director: 'Vijay Krishna Acharya', cast: 'Aamir Khan, Katrina Kaif, Abhishek Bachchan, Uday Chopra',release: '28 April 2017 ',description: "Dhoom 3 marked the third installment of the hit Dhoom franchise. The action packed thriller Aamir plays Sahir, a circus entertainer who attempts for a bank robbery in Chicago in order to take revenge of his father's death. Inspector Jai and Ali played by Abhishek and Uday play the cops on duty as they investigate the case. This marks the third Aamir starrer to the list of the highest grosses in the last decade.", img: img38, time: '10am to 1pm'},
    {id: 40, title: 'Dhoom 3', director: 'Vijay Krishna Acharya', cast: 'Aamir Khan, Katrina Kaif, Abhishek Bachchan, Uday Chopra',release: '28 April 2017 ',description: "Dhoom 3 marked the third installment of the hit Dhoom franchise. The action packed thriller Aamir plays Sahir, a circus entertainer who attempts for a bank robbery in Chicago in order to take revenge of his father's death. Inspector Jai and Ali played by Abhishek and Uday play the cops on duty as they investigate the case. This marks the third Aamir starrer to the list of the highest grosses in the last decade.", img: img39, time: '10am to 1pm'}
]

export default MovieData;